-- The goal of nvim-treesitter is both to provide a simple and easy way to use the interface for tree-sitter in Neovim and to provide some basic functionality such as highlighting based on it.
-- https://github.com/nvim-treesitter/nvim-treesitter
return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
	},
	build = ":TSUpdate",
	event = "VeryLazy",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"c_sharp",
			"c",
			"cpp",
			"css",
			"csv",
			"diff",
			"dockerfile",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"html",
			"java",
			"javascript",
			"jsdoc",
			"json",
			"json5",
			"kotlin",
			"lua",
			"lua",
			"luadoc",
			"luadoc",
			"luau",
			"markdown",
			"pascal",
			"php",
			"phpdoc",
			"python",
			"regex",
			"rust",
			"scss",
			"sql",
			"tsx",
			"twig",
			"vim",
			"vimdoc",
		},
		highlight = {
			enabled = true,
		}, 
		indent = {
			enabled = true,
		},
		textobjects = {
			select = {
				enable = true,
				lookahead = true,
				keymaps = {
					["af"] = "@function.outer",
					["if"] = "@function.inner",
					["ac"] = "@conditional.outer",
					["ic"] = "@conditional.inner",
					["al"] = "@loop.outer",
					["il"] = "@loop.inner",
				},
			},
		},
	},
}
